### ISSUE TITLE
Concepts.tsv

### ISSUE THREAD

**Issue by natalia-morozova** [lexibank/backstromnorthernpakistan#2]
@LinguList, should I upload a concepts.tsv file or a reference to the lists on Concepticon would be enough? I have noticed that concepts.tsv was removed from some lexibank datasets. If you prefer me to duplicate the mappings here, I would create one file for all the lists as in [diacl](https://github.com/lexibank/diacl/blob/master/etc/concepts.csv).

**Comment by LinguList** [comment]
I'd like to see the differences in the data, I would also say: it does not hurt to have them all separately in Concepticon. And per dataset, you'll only need one. So the procedure: make one concepts.tsv file now, we prepare that for submitting to concepticon, and once this is done we actually do this, okay?
