### ISSUE TITLE
Orthography profile

### ISSUE THREAD

**Issue by natalia-morozova** [lexibank/backstromnorthernpakistan#5]
I am not sure about the right way of creating the profile for this dataset. @LinguList, would you provide me with instructions? Otherwise, I could just take care of the unrefined profile if you upload it to the repository.

**Comment by LinguList** [comment]
if you have a first cldf which has forms, load most recent lingpy from github, and then type:

```
lingpy profile -i cldf/forms.csv -o etc/orthography.tsv --cldf --column=form --clts --context
```

If that doens't work, I'll run it and upload it.

**Comment by natalia-morozova** [comment]
Thank you! I got the following error: 
KeyError: 'language_name'
I manually added a new column, so it worked (will not push the changes in forms.csv, of course).

**Comment by LinguList** [comment]
so you have an old version of lingpy, not the most recent one, but it's okay, maybe it's even the one I merged just now. Well done, to get it worked!
